version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet: